( define square_function ( lambda ( n ) ( * n n ) ) )
( define cubic_function ( lambda ( n ) ( * n (square_function n) ) ) )
( define even_sums (lambda (n) (if (= n 0)
                                   0
                                   (if (even? n)
                                       (+ n (even_sums (- n 1)))
                                       (even_sums (- n 1)))
                                   ) ))
( define list_square_function ( lambda ( list_object )
                                 ( if  (= (length list_object) 0 )
                                      (list) 
                                      (append  (list (square_function (car list_object))) (list_square_function (cdr list_object)))
                                 )
                             )
)
( define list_cube_function ( lambda ( list_object )
                                 ( if  (= (length list_object) 0 )
                                      (list) 
                                      (append  (list (cubic_function (car list_object))) (list_cube_function (cdr list_object)))
                                 )
                             )
)
( define higher_order_function ( lambda (listed_values n)
                                  (if ( = n 2 )
                                      (list_square_function listed_values)
                                      (list_cube_function listed_values)
  )))
(higher_order_function  (list 3 4 5) 3)
(list_square_function (list 7 3 4 5))
(even_sums 5)
(cubic_function 2)
(list_cube_function (list 7 3 4 5)) 
